# Directives - The actual instructions or commands that tell Nginx what to do
# Contexts - Groups of related directives that apply to a certain part of the configuration

events {}

http {
  server {
    listen 80; # If configuring server to listen on port 443. 443 is the standard port for HTTPS traffic, enabling SSL.
    
    # ssl_certificate path location of crt
    # ssl_certificate_key path location of crt key

    # React frontend
    location / {
      proxy_pass http://frontend:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Django backend
    # proxy_pass tells Nginx to pass the request to another server, like a reverse proxy
    # proxy_set_header Host $host; - Passing client information to backend
    # proxy_set_header X-Real-IP $remote_addr - actual IP address of the client
    location /api/ {
      proxy_pass http://backend:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}