events {}

http {
  server {
    listen 80;

    # React frontend
    location / {
      proxy_pass http://frontend:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Django backend
    # proxy_pass tells Nginx to pass the request to another server, like a reverse proxy
    # proxy_set_header Host $host; - Passing client information to backend
    # proxy_set_header X-Real-IP $remote_addr - actual IP address of the client
    location /api/ {
      proxy_pass http://backend:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}